### ISSUE TITLE
Enable the player to move the camera by pressing wasd and the arrow buttons.

### ISSUE THREAD

**Issue by YvesImmer** [bfh/NewWorld#11]
If possible also look into moving it by having the mouse at the borders of the camera.

**Comment by YvesImmer** [comment]
Putting it in update is not nice. Every frame it has to do four If statements, more if we add wasd. Moving by having the mouse at the edges is mostly uncompatible.
I was more imagining something like an event when one of the Buttons is pressed that then triggers the movement. So, just one Method that moves the camera, based on the input it changes directions. 
Additionally The Keys and the Speed should be public Variables so they can be changes from elsewhere.

**Comment by l00mi** [comment]
Working
