### ISSUE TITLE
Planung Game Development

### ISSUE THREAD

**Issue by l00mi** [bfh/NewWorld#3]
Dies ist die Antwort von Marc welcher wir ihr lessen könnt, sich bedeuten besser auskennt wie man ein Game Design plant. Bitte schaut euch seine Antwort an wir werden schauen welche Elemente davon für euer Projekt umzusetzen sind.

> Salut Michael,
> 
> Das 'Equivalent' zu User-Stories im Falle von Games waere wohl das Game Design Document (GDD). Wobei gewisse Spiele durchaus von den klassischen Use Cases profitieren koennen. 
> 
> Das GDD dient dazu, dass ideen komplett durchdacht werden bevor man ans Implementieren geht. Eine witere Rolle des GDD ist es die Vision des Spiels zu dokumentieren und alle beteiligten auf der selben Linie zu halten.
> 
> Hier einige Key Aspekte welche ein GDD enthalten sollte:
> 
> Concept
> Pitch / High Concept: Ein auf den Punkt gebrachter Satz oder zwei welcher den Kern der Spielidee beschreibt. Einige must haves in diesem Paragraph sind folgendes: Camera (first person, third person, top down etc.) Genre (Shooter, Racing, Strategy etc.) Theme (Medieval, Sci-fi, Fantasy etc.)
> 
> Ex.: Super Mario World is a 2D side-scrolling platformer set in a fantasy world called the Mushroom Kingdom. The player has to defeat or avoid enemies to make it to the end of a level.
> 
> Pillars: Pillars bilden den Kern auf dem das Spiel aufbaut. Pillars dienen als Grundlage wenn es darum geht Features fuer das Spiel zu designend. Diese Features muessen von den Pillars supportet werden.
> 
> Ex.: Teamwork, Approachable, Exploration. 
> 
> Zwei bis Drei Pillars sind in der Regel genug. Hier ist ein Interessanter Artikel zu Diablo 2 mit seinen 7 Pillarn, was zu vielen Problemen gefuehrt hat. https://www.diabloii.net/blog/comments/diablo-3s-seven-design-pillars-2 
> 
> Features
> Features sind dinge wie Movement oder Combat. In den je nach Spiel sind diese Features natuerlich groesser oder kleiner. Die features bestehen natuerlich aus sub-features Wie zum Beispiel Movement.
> 
> Movement: Jumping, Crouching, Walking, Running, Dodge roll etc.
> 
> All diese sub features sollten definiert und zu einem gewissen grad durchgedacht und niedergeschrieben werden.
> 
> Character 
> Wen kontrollieren wir, was ist unsere motivation. Was koennen wir mit dem Character machen? Im Falle von Mario wuerde ich hier auch alle verschiedenen Items auflisten und was fuer einen Effekt diese auf den Charakter haben.
> 
> Camera
> Wie funktioniert die Kamera? Bei einem Side-scroller kann es sein, dass die Kamera dynamisch heraus "zoomt" wenn der Charakter schneller wird. Wie sich die Kamera in welchen situationen verhalet sollte hier entschieden und beschrieben werden. Moeglichst in einer Form in welcher ein Programmiere das ganze umsetzen kann ohne die Designer zu fragen.
> 
> Controls
> Welche knoepfe machen was? Im einfachsten Falle ist hier ein Diagram einer Tastatur und/oder eines Kontrollers. 
> 
> 
> Die letzten drei Punkte werden auch "The 3 Cs" genannt und sollten bei jedem Spiel definiert seind. Natuerlich besteht ein GDD aus mehr als nur diesen paar titeln aber fuer ein kleines Projekt sollte das ausreichen. 
> 
> Es kommt durchaus vor, dass diese Dokumente mehrere hundert Seiten lang werden. Und bei vielen Projekten werden die Dokumente nicht ganz up-to-date gehalten, was dazu fuehrt, dass man am ende ein voellig nutzloses GDD hat. 
> 
> Das GDD hat jedoch den grossen Nutzen, dass es die Designer zwingt das ganze Spiel von anfang an zu beschreiben. Was hoffentlich dazu fuehrt, dass viele zukuenftige Konflikte von Features bereits in der Design Phase entdeckt werden koennen.
> 
> Viele Studios verwenden zudem Wiki's heutzutage anstelle von einem Kompletten GDD.
> 
> Hoffe das hilft etwas, leider ist Game Design sehr schwer in einen "best practice" Prozess zu packen.
> 
> LG
> Marc

**Comment by YvesImmer** [comment]
Please close the issue when you've read it ty.
